/*
 * Copyright (c) 2021-2025 Team Galacticraft
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package dev.galacticraft.machinelib.api.menu;

import dev.galacticraft.machinelib.api.block.entity.GeneratorMachineBlockEntity;
import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.MenuType;
import org.jetbrains.annotations.NotNull;

/**
 * A simple menu for machines that generate energy
 *
 * @param <Machine> The type of machine block entity
 * @see MachineMenu
 */
public class GeneratorMachineMenu<Machine extends GeneratorMachineBlockEntity> extends MachineMenu<Machine> {
    /**
     * The current amount of energy being generated by the machine.
     */
    private long energyGeneration = 0;

    /**
     * Constructs a new generator menu.
     *
     * @param type The type of machine associated with this menu.
     * @param syncId The sync id for this menu.
     * @param player The player who is interacting with this menu.
     * @param machine The machine this menu is for.
     */
    public GeneratorMachineMenu(MenuType<? extends GeneratorMachineMenu<Machine>> type, int syncId, @NotNull Player player, @NotNull Machine machine) {
        super(type, syncId, player, machine);
        
        this.energyGeneration = machine.getEnergyGeneration();
    }

    /**
     * Constructs a new generator menu for a machine.
     *
     * @param type The type of machine associated with this menu.
     * @param syncId The sync id for this menu.
     * @param inventory The inventory of the player interacting with this menu.
     * @param pos the position of the machine being opened
     */
    protected GeneratorMachineMenu(MenuType<? extends GeneratorMachineMenu<Machine>> type, int syncId, @NotNull Inventory inventory, @NotNull BlockPos pos) {
        super(type, syncId, inventory, pos);
        
        this.energyGeneration = this.be.getEnergyGeneration();
    }

    /**
     * Constructs a new generator menu for a machine.
     *
     * @param type The type of machine associated with this menu.
     * @param syncId The sync id for this menu.
     * @param inventory The inventory of the player interacting with this menu.
     * @param pos the position of the machine being opened
     * @param invX The x position of the inventory in the menu.
     * @param invY The y position of the inventory in the menu.
     */
    public GeneratorMachineMenu(MenuType<? extends GeneratorMachineMenu<Machine>> type, int syncId, @NotNull Inventory inventory, @NotNull BlockPos pos, int invX, int invY) {
        super(type, syncId, inventory, pos, invX, invY);
        
        this.energyGeneration = this.be.getEnergyGeneration();
    }

    /**
     * Registers the sync handlers for the menu.
     */
    @Override
    public void registerData(@NotNull MenuData data) {
        super.registerData(data);

        data.registerLong(this.be::getEnergyGeneration, this::setEnergyGeneration);
    }

    /**
     * {@return the current energy generation of the machine}
     */
    public long getEnergyGeneration() {
        return this.energyGeneration;
    }

    /**
     * Sets the energy generation value of the machine.
     *
     * @param energyGeneration The new energy generation value.
     */
    public void setEnergyGeneration(long energyGeneration) {
        this.energyGeneration = energyGeneration;
    }
}
