name: Commit

on:
  push:
    branches: [ 'minecraft/*' ]

jobs:
  validate-wrapper:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  license-headers:
    needs: validate-wrapper
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: License headers
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkLicenses
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/minecraft/') }}

  build:
    needs: validate-wrapper
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x checkLicenses
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/minecraft/') }}

  test:
    needs: [validate-wrapper, build]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Gametest
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runGametest
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/minecraft/') }}

  publish:
    needs: [ validate-wrapper, build, test ]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/minecraft/') }}
        env:
          PRE_RELEASE: false
          NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_RELEASE_URL }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
