name: Crowdin Translation Push

on:
  workflow_dispatch:
  push:
    branches: [ 'minecraft/*' ]
    paths:
      - 'src/main/resources/assets/machinelib/lang/en_us.json'

jobs:
  crowdin_push:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy translations
        run: cp src/main/resources/assets/machinelib/lang/en_us.json machinelib.json

      - name: Crowdin Push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false

          source: 'machinelib.json'
          translation: 'src/main/resources/assets/machinelib/lang/%locale_with_underscore%.json'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          base_url: ${{ secrets.CROWDIN_BASE_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}